# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b06b97955fdbb273f4895f2d6d089d7463587413812e805fc746902537e4f8919b4281ebc29abd5beafce297adb31fecfe3a520d68c8230bf5d3e7730d0b1c1f

test:
  secret_key_base: 5bb273e4131e4260d72099f88cbe9b1ff146f44a4c54925763c18fae549f40e106f674632d1a8e81ee11e750ba1cc22249eaefa9ec4db601ef00df2b17b9cdc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
